name: Lint

on:
  push:
    branches:
      - master
    paths:
      - 'radical.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

# This step aims to check if user updated dict file when workflow is tiggered manually
      - name: Check update
        id: check_update
        run: |
          $ChangeFile = git diff-tree -r --name-only HEAD^ HEAD
          if ( 'radical.yaml' -in $ChangeFile ) {
            "updated=1" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
          else {
            "updated=0" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Lint
        if: steps.check_update.outputs.updated == '1'
        run: |
          python lint.py

      - name: Commit
        if: steps.check_update.outputs.updated == '1'
        run: |
          $ErrorActionPreference = 'Break'
          $CommitInfo = (git log --pretty=%B -1)[0]
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          $Status = git status --porcelain
          if ( $Status ) {
          "Commit lint"
          git add 'radical.yaml'
          git commit -m "lint: $CommitInfo" && git push origin master
          }

# remember to check repo secret DISPATCH_PAT. this pat should be authed the read and write permession of target repo.
# It may out of date since PAT only allows user to set one year time limit
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
# client_payload can pass messge to target repo. Access it with github.event.client_payload.<name>
      - name: tigger workflow
        uses: actions/github-script@v7
        if: ${{ steps.check_update.outputs.updated == '1' && github.repository == 'mirtlecn/chaizi-re' }}
        with:
          github-token: ${{ secrets.DISPATCH_PAT }}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: 'mirtlecn',
              repo: 'rime-radical-pinyin',
              event_type: 'chaizi_update',
              client_payload: {
                "version": "2024.03.25"
              }
            })
            console.log(result);
